---
editor_options: 
  markdown: 
    wrap: 85
---

# The Machine Learning Landscape

When most people hear "**Machine Learning**," they picture a robot: a dependable but‐
ler or a deadly Terminator depending on who you ask. But Machine Learning is not just
a futuristic fantasy, it's already here. In fact, it has been around for decades in
some specialized applications, such as Optical Character Recognition (OCR). But the
first ML application that really became mainstream, improving the lives of hundreds
of millions of people, took over the world back in the 1990s: it was the spam filter.
Not exactly a self-aware Skynet, but it does technically qualify as Machine Learning
(it has actually learned so well that you seldom need to flag an email as spam any‐
more). It was followed by hundreds of ML applications that now quietly power hun‐
dreds of products and features that you use regularly, from better recommendations to
voice search.

Where does Machine Learning start and where does it end? What exactly does it mean
for a machine to learn something? If I download a copy of Wikipedia, has my computer
really "learned" something? Is it suddenly smarter? In this chapter we will start by
clarifying what Machine Learning is and why you may want to use it.

Then, before we set out to explore the Machine Learning continent, we will take a
look at the map and learn about the main regions and the most notable landmarks:
supervised versus unsupervised learning, online versus batch learning, instance-
based versus model-based learning. Then we will look at the workflow of a typical ML
project, discuss the main challenges you may face, and cover how to evaluate and
fine-tune a Machine Learning system.

This chapter introduces a lot of fundamental concepts (and jargon) that every data
scientist should know by heart. It will be a high-level overview (the only chapter
without much code), all rather simple, but you should make sure everything is
crystal-clear to you before continuing to the rest of the book. So grab a coffee and
let's get started!

## What Is Machine Learning?

Machine Learning is the science (and art) of programming computers so they can learn
from data.

Here is a slightly more general definition:

*[Machine Learning is the] field of study that gives computers the ability to learn
without being explicitly programmed.* ---Arthur Samuel, 1959

*And a more engineering-oriented one: A computer program is said to learn from
experience E with respect to some task T and some performance measure P, if its
performance on T, as measured by P, improves with experience E.* ---Tom Mitchell,
1997

For example, your spam filter is a Machine Learning program that can learn to flag
spam given examples of spam emails (e.g., flagged by users) and examples of regular
(nonspam, also called "ham") emails. The examples that the system uses to learn are
called the training set. Each training example is called a training instance (or
sample). In this case, the task T is to flag spam for new emails, the experience E is
the training data, and the performance measure P needs to be defined; for example,
you can use the ratio of correctly classified emails. This particular performance
measure is called accuracy and it is often used in classification tasks.

If you just download a copy of Wikipedia, your computer has a lot more data, but it
is not suddenly better at any task. Thus, it is not Machine Learning.

## Why Use Machine Learning?

Consider how you would write a spam filter using traditional programming techniques:

1.  First you would look at what spam typically looks like. You might notice that
    some words or phrases (such as "4U," "credit card," "free," and "amazing") tend
    to come up a lot in the subject. Perhaps you would also notice a few other
    patterns in the sender's name, the email's body, and so on.

2.  You would write a detection algorithm for each of the patterns that you noticed,
    and your program would flag emails as spam if a number of these patterns are
    detected.

3.  You would test your program, and repeat steps 1 and 2 until it is good enough.
